import { ArmoryItem, EquippedGear } from '../types';

export const ARMORY_ITEMS: ArmoryItem[] = [
  // ==========================================
  // SHIELDS (6 Unique Shields - Points Progression)
  // ==========================================
  {
    id: 'shield_katfjord_round',
    name: 'Katfjord Pine Roundshield',
    category: 'shield',
    requiredPoints: 0,
    rarity: 'common',
    description: 'Standard issue Norse round shield crafted from seasoned Katfjord pine and banded with raw iron.',
    perkDescription: 'Standard 85% melee and projectile damage deflection when held.',
    blockBonus: 0,
    primaryColor: '#991b1b',
    accentColor: '#f59e0b',
    specialEffect: 'none',
  },
  {
    id: 'shield_wolf_targe',
    name: 'Wolf-Pelt Iron Targe',
    category: 'shield',
    requiredPoints: 200,
    rarity: 'uncommon',
    description: 'Sturdy oak shield stretched with tundra dire-wolf hide and studded with heavy iron rivets.',
    perkDescription: '+6% Deflection efficiency. Consumes 15% less stamina while holding block.',
    blockBonus: 6,
    primaryColor: '#475569',
    accentColor: '#e2e8f0',
    specialEffect: 'none',
  },
  {
    id: 'shield_bronze_sun',
    name: 'Sol-Kite Sun Disk',
    category: 'shield',
    requiredPoints: 600,
    rarity: 'rare',
    description: 'A radiant kite shield hammered in bronze by solstice priests, reflecting the blinding sun of Freyr.',
    perkDescription: '+12% Deflection. Blinds nearby melee attackers when timing a perfect parry.',
    blockBonus: 12,
    primaryColor: '#b45309',
    accentColor: '#fde047',
    specialEffect: 'gold_glow',
  },
  {
    id: 'shield_frostfang_heater',
    name: 'Frostfang Glacial Buckler',
    category: 'shield',
    requiredPoints: 1100,
    rarity: 'epic',
    description: 'Carved from blue glacial ice and enchanted iron taken from Frostfang raider outposts.',
    perkDescription: '+18% Deflection. 20% chance to chill attackers on impact, slowing their swing.',
    blockBonus: 18,
    primaryColor: '#0284c7',
    accentColor: '#38bdf8',
    specialEffect: 'frost',
  },
  {
    id: 'shield_dragon_scale',
    name: 'Jormungandr Dragoncrest',
    category: 'shield',
    requiredPoints: 1800,
    rarity: 'legendary',
    description: 'Forged from iridescent abyssal scales of the Midgard Serpent. Shimmers with untamable sea wrath.',
    perkDescription: '+24% Deflection. Blocks 50% of boss ground-slam shockwave damage.',
    blockBonus: 24,
    primaryColor: '#065f46',
    accentColor: '#34d399',
    specialEffect: 'lightning',
  },
  {
    id: 'shield_aegis_valhalla',
    name: 'Aegis of Valhalla',
    category: 'shield',
    requiredPoints: 2600,
    rarity: 'mythic',
    description: 'Sacred golden pavilion shield carried by Odin’s Einherjar. Glows with perpetual celestial aura.',
    perkDescription: '+30% Deflection. Absorbs 95% of all impact forces and restores 5 stamina per deflect.',
    blockBonus: 30,
    primaryColor: '#854d0e',
    accentColor: '#fef08a',
    specialEffect: 'gold_glow',
  },

  // ==========================================
  // SWORDS & WEAPONS (6 Unique Weapons - Points Progression)
  // ==========================================
  {
    id: 'weapon_bearded_axe',
    name: 'Iron Bearded Handaxe',
    category: 'weapon',
    requiredPoints: 0,
    rarity: 'common',
    description: 'Trusty Norse bearded axe designed for felling tall pines and shattering raider shields alike.',
    perkDescription: 'Base attack damage: 35. Swift cleave speed.',
    damageBonus: 0,
    primaryColor: '#475569',
    accentColor: '#78350f',
    specialEffect: 'none',
  },
  {
    id: 'weapon_raider_broadsword',
    name: 'Raider Pattern Broadsword',
    category: 'weapon',
    requiredPoints: 250,
    rarity: 'uncommon',
    description: 'Double-edged steel blade captured during coastal raids, balanced for quick lunges and wide arcs.',
    perkDescription: '+6 Weapon Attack Damage. Increases critical strike chance by 5%.',
    damageBonus: 6,
    primaryColor: '#64748b',
    accentColor: '#991b1b',
    specialEffect: 'none',
  },
  {
    id: 'weapon_runic_ulfberht',
    name: 'Runic Ulfberht Longsword',
    category: 'weapon',
    requiredPoints: 750,
    rarity: 'rare',
    description: 'Famous crucible steel stamped with mystical +VLFBERH+T runes that hum with runic fervor.',
    perkDescription: '+12 Weapon Attack Damage. Strikes shatter wooden enemy barricades faster.',
    damageBonus: 12,
    primaryColor: '#334155',
    accentColor: '#38bdf8',
    specialEffect: 'lightning',
  },
  {
    id: 'weapon_frostfang_cleaver',
    name: 'Frostfang Glacial Greatsword',
    category: 'weapon',
    requiredPoints: 1300,
    rarity: 'epic',
    description: 'A heavy two-handed greatsword infused with permafrost runes from the northern ice peaks.',
    perkDescription: '+18 Weapon Attack Damage. Critical hits release a blast of frosty particles.',
    damageBonus: 18,
    primaryColor: '#0369a1',
    accentColor: '#bae6fd',
    specialEffect: 'frost',
  },
  {
    id: 'weapon_blood_reaver',
    name: 'Bloodhound Berserker Axe',
    category: 'weapon',
    requiredPoints: 2000,
    rarity: 'legendary',
    description: 'A twin-headed battleaxe bathed in the blood of defeated warlords. Vibrates with battle frenzy.',
    perkDescription: '+24 Weapon Attack Damage. 30% chance on hit to grant brief burst sprint speed.',
    damageBonus: 24,
    primaryColor: '#7f1d1d',
    accentColor: '#f87171',
    specialEffect: 'blood_rune',
  },
  {
    id: 'weapon_gram_dragon_slayer',
    name: 'Gram, Blade of Sigurd',
    category: 'weapon',
    requiredPoints: 2800,
    rarity: 'mythic',
    description: 'The mythic golden blade that slew the dragon Fafnir. Tempered in starlight and dwarven dragonfire.',
    perkDescription: '+32 Weapon Attack Damage. Generates divine golden shockwave trails on each swing.',
    damageBonus: 32,
    primaryColor: '#a16207',
    accentColor: '#fef08a',
    specialEffect: 'gold_glow',
  },

  // ==========================================
  // HEADWEAR & HELMETS (6 Unique Headwear - Points Progression)
  // ==========================================
  {
    id: 'headwear_nasal_helm',
    name: 'Katfjord Nasal Helm',
    category: 'headwear',
    requiredPoints: 0,
    rarity: 'common',
    description: 'Traditional conical iron spangenhelm with a solid nasal guard and leather strapping.',
    perkDescription: 'Standard warrior skull protection.',
    staminaBonus: 0,
    primaryColor: '#475569',
    accentColor: '#d97706',
    specialEffect: 'none',
  },
  {
    id: 'headwear_berserker_cowl',
    name: 'Berserker Bear-Pelt Hood',
    category: 'headwear',
    requiredPoints: 300,
    rarity: 'uncommon',
    description: 'The sacred cowl of an apex brown bear from the Jotunheim ridges, invoking primal ferocity.',
    perkDescription: '+10 Maximum Stamina. Intimidating presence reduces raider stagger resistance.',
    staminaBonus: 10,
    primaryColor: '#78350f',
    accentColor: '#b45309',
    specialEffect: 'none',
  },
  {
    id: 'headwear_spectacle_helm',
    name: 'Gjermundbu Spectacle Helm',
    category: 'headwear',
    requiredPoints: 800,
    rarity: 'rare',
    description: 'Masterfully forged iron mask with iconic spectacle eye-guards and aventail chainmail draped to the shoulders.',
    perkDescription: '+15 Maximum Stamina. Increases field visibility in heavy Fjord mist and snow.',
    staminaBonus: 15,
    primaryColor: '#334155',
    accentColor: '#e2e8f0',
    specialEffect: 'none',
  },
  {
    id: 'headwear_valkyrie_wings',
    name: 'Winged Valkyrie Crest',
    category: 'headwear',
    requiredPoints: 1400,
    rarity: 'epic',
    description: 'Silver and azure steel helmet crowned with swan-wing plumes worn by psychopomp battlefield maidens.',
    perkDescription: '+20 Maximum Stamina. +10% faster stamina recovery after sprinting and jumping.',
    staminaBonus: 20,
    primaryColor: '#0e7490',
    accentColor: '#e0f2fe',
    specialEffect: 'frost',
  },
  {
    id: 'headwear_raven_crown',
    name: 'Crown of Huginn & Muninn',
    category: 'headwear',
    requiredPoints: 2100,
    rarity: 'legendary',
    description: 'Obsidian coronet bearing carved raven silhouettes that whisper enemy tactical weaknesses.',
    perkDescription: '+25 Maximum Stamina. Critical hits deal 200% damage instead of 180%.',
    staminaBonus: 25,
    primaryColor: '#172554',
    accentColor: '#93c5fd',
    specialEffect: 'lightning',
  },
  {
    id: 'headwear_allfather_diadem',
    name: 'Diadem of the Allfather',
    category: 'headwear',
    requiredPoints: 2750,
    rarity: 'mythic',
    description: 'A radiant golden crown carved with Yggdrasil branches and ancient elder futhark runes of high dominion.',
    perkDescription: '+35 Maximum Stamina. Emits a divine golden crown aura and increases Valor rewards by 20%.',
    staminaBonus: 35,
    primaryColor: '#a16207',
    accentColor: '#fef08a',
    specialEffect: 'gold_glow',
  },
];

export const DEFAULT_EQUIPPED_GEAR: EquippedGear = {
  weaponId: 'weapon_bearded_axe',
  shieldId: 'shield_katfjord_round',
  headwearId: 'headwear_nasal_helm',
};

export function getUnlockedArmoryItems(currentPoints: number): ArmoryItem[] {
  return ARMORY_ITEMS.filter((item) => currentPoints >= item.requiredPoints);
}

export function getNextArmoryUnlock(currentPoints: number): ArmoryItem | null {
  const lockedItems = ARMORY_ITEMS.filter((item) => currentPoints < item.requiredPoints).sort(
    (a, b) => a.requiredPoints - b.requiredPoints
  );
  return lockedItems.length > 0 ? lockedItems[0] : null;
}
