import {
  GamepassItem,
  GBPCurrencyPack,
  SagaPassTier,
  VikingPet,
  VikingMount,
  TycoonBuilding,
  WeaponSkill,
  AchievementBadge,
  TradeOffer,
  PetId,
  FishSpecies,
  ArrowDefinition,
  BuildableStructureBlueprint,
  PetEvolutionData,
  MountArmorPiece,
  ClanConquestTower,
} from '../types';

export const GBP_CURRENCY_PACKS: GBPCurrencyPack[] = [
  {
    id: 'gbp_pouch_099',
    name: "Thrall's Coin Pouch",
    subtitle: 'Starter Sterling Silver & Valor Top-Up',
    priceGBP: 0.99,
    silverAmount: 500,
    bonusValor: 100,
    freeWheelSpins: 0,
    badgeText: 'Starter',
  },
  {
    id: 'gbp_satchel_249',
    name: "Raider's Silver Satchel",
    subtitle: '+15% Extra Silver + 1 Bonus Rune Spin',
    priceGBP: 2.49,
    silverAmount: 1400,
    bonusValor: 300,
    freeWheelSpins: 1,
    badgeText: '+15% Bonus',
  },
  {
    id: 'gbp_chest_499',
    name: "Huscarl's War Chest",
    subtitle: '+25% Extra Silver + 2 Bonus Rune Spins',
    priceGBP: 4.99,
    silverAmount: 3200,
    bonusValor: 750,
    freeWheelSpins: 2,
    badgeText: '+25% Value',
    popular: true,
  },
  {
    id: 'gbp_treasury_999',
    name: "Jarl's Royal Treasury",
    subtitle: '+45% Extra Silver + 5 Bonus Rune Spins',
    priceGBP: 9.99,
    silverAmount: 7500,
    bonusValor: 1800,
    freeWheelSpins: 5,
    badgeText: 'Most Popular',
    popular: true,
  },
  {
    id: 'gbp_vault_1999',
    name: "High King's Vault",
    subtitle: 'Massive Katfjord War Chest + 10 Rune Spins',
    priceGBP: 19.99,
    silverAmount: 18000,
    bonusValor: 4500,
    freeWheelSpins: 10,
    badgeText: '+80% Bonus',
  },
  {
    id: 'gbp_sovereign_4999',
    name: "Odin's Sovereign Hoard",
    subtitle: '50,000 Silver + Unlocks All 4 VIP Gamepasses & Gold Pass',
    priceGBP: 49.99,
    silverAmount: 50000,
    bonusValor: 15000,
    freeWheelSpins: 25,
    badgeText: 'All VIP Passes Included',
    includesAllPasses: true,
  },
];

export const INITIAL_GAMEPASSES: GamepassItem[] = [
  {
    id: 'gp_double_rewards',
    name: '2x Valor & Silver Pass',
    tagline: 'Double all combat, raid, and gathering spoils permanently',
    description:
      'Every Raider slain, Boss conquered, tree chopped, and quest claimed grants 200% Silver Coins and Valor Honor.',
    priceSilver: 350,
    priceValor: 250,
    priceGBP: 2.99,
    owned: false,
    perkType: 'double_rewards',
    badgeText: '2x Spoils',
  },
  {
    id: 'gp_golden_ship',
    name: 'VIP Golden Drakkar Sail',
    tagline: '+65% Longship sailing speed and royal golden hull trim',
    description:
      'Upgrades the Katfjord Drakkar with Odin’s wind blessing, slicing across the fjord at 1.65x speed.',
    priceSilver: 300,
    priceValor: 200,
    priceGBP: 2.49,
    owned: false,
    perkType: 'golden_ship',
    badgeText: '+65% Ship Speed',
  },
  {
    id: 'gp_resource_magnet',
    name: 'Dwarven Resource Magnet',
    tagline: '2x Timber & Iron harvest yield + passive +4 Silver/sec',
    description:
      'Automatically doubles Timber and Iron mined per swing and generates passive Silver tribute into your pouch.',
    priceSilver: 400,
    priceValor: 300,
    priceGBP: 3.99,
    owned: false,
    perkType: 'resource_magnet',
    badgeText: 'Auto-Tribute',
  },
  {
    id: 'gp_speed_wings',
    name: 'Hermod’s Speed & Sky Leap',
    tagline: '+30% movement speed and +35% higher jumps for Sky Obby',
    description:
      'Channel the messenger god’s swiftness to sprint across battlefields and leap effortlessly across Valhalla Sky Obby platforms.',
    priceSilver: 280,
    priceValor: 180,
    priceGBP: 1.99,
    owned: false,
    perkType: 'speed_wings',
    badgeText: '+30% Agility',
  },
];

export const INITIAL_SAGA_PASS_TIERS: SagaPassTier[] = [
  {
    tier: 1,
    requiredValor: 0,
    freeRewardLabel: '100 Silver Pouch',
    freeSilver: 100,
    goldRewardLabel: '250 Silver + 100 Valor',
    goldSilver: 250,
    goldValor: 100,
    claimedFree: false,
    claimedGold: false,
  },
  {
    tier: 2,
    requiredValor: 150,
    freeRewardLabel: '150 Silver Pouch',
    freeSilver: 150,
    goldRewardLabel: '350 Silver + 150 Valor',
    goldSilver: 350,
    goldValor: 150,
    claimedFree: false,
    claimedGold: false,
  },
  {
    tier: 3,
    requiredValor: 350,
    freeRewardLabel: '220 Silver Pouch',
    freeSilver: 220,
    goldRewardLabel: '500 Silver + 220 Valor',
    goldSilver: 500,
    goldValor: 220,
    claimedFree: false,
    claimedGold: false,
  },
  {
    tier: 4,
    requiredValor: 650,
    freeRewardLabel: '300 Silver Pouch',
    freeSilver: 300,
    goldRewardLabel: '700 Silver + 350 Valor',
    goldSilver: 700,
    goldValor: 350,
    claimedFree: false,
    claimedGold: false,
  },
  {
    tier: 5,
    requiredValor: 1000,
    freeRewardLabel: '450 Silver Chest',
    freeSilver: 450,
    goldRewardLabel: '1,000 Silver + 500 Valor',
    goldSilver: 1000,
    goldValor: 500,
    claimedFree: false,
    claimedGold: false,
  },
  {
    tier: 6,
    requiredValor: 1500,
    freeRewardLabel: '600 Silver Chest',
    freeSilver: 600,
    goldRewardLabel: '1,400 Silver + 750 Valor',
    goldSilver: 1400,
    goldValor: 750,
    claimedFree: false,
    claimedGold: false,
  },
  {
    tier: 7,
    requiredValor: 2200,
    freeRewardLabel: '850 Silver Hoard',
    freeSilver: 850,
    goldRewardLabel: '2,000 Silver + 1,100 Valor',
    goldSilver: 2000,
    goldValor: 1100,
    claimedFree: false,
    claimedGold: false,
  },
  {
    tier: 8,
    requiredValor: 3000,
    freeRewardLabel: '1,200 Silver Hoard',
    freeSilver: 1200,
    goldRewardLabel: '3,000 Silver + 1,600 Valor',
    goldSilver: 3000,
    goldValor: 1600,
    claimedFree: false,
    claimedGold: false,
  },
];

export const INITIAL_PETS: VikingPet[] = [
  {
    id: 'pet_odin_raven',
    name: 'Huginn the All-Seeing',
    species: 'Odin’s Runic Raven',
    rarity: 'rare',
    buffDescription: '+25% Valor Honor gained & +12 Attack Damage',
    damageBonus: 12,
    valorMultiplier: 1.25,
    regenPerSec: 1,
    primaryColor: '#1e293b',
    accentColor: '#38bdf8',
    unlocked: true,
    count: 1,
  },
  {
    id: 'pet_fenrir_pup',
    name: 'Fenrir Dire Pup',
    species: 'Silver Frost Wolf',
    rarity: 'epic',
    buffDescription: '+24 Attack Damage & +15% Valor Honor',
    damageBonus: 24,
    valorMultiplier: 1.15,
    regenPerSec: 2,
    primaryColor: '#64748b',
    accentColor: '#f43f5e',
    unlocked: false,
    count: 0,
  },
  {
    id: 'pet_golden_boar',
    name: 'Gullinbursti',
    species: 'Freyr’s Golden Boar',
    rarity: 'legendary',
    buffDescription: '+30 Attack Damage & +5 HP/sec Healing Aura',
    damageBonus: 30,
    valorMultiplier: 1.35,
    regenPerSec: 5,
    primaryColor: '#facc15',
    accentColor: '#fef08a',
    unlocked: false,
    count: 0,
  },
  {
    id: 'pet_frost_dragon',
    name: 'Nidhogg Frost Wyrm',
    species: 'Mythic Glacier Dragon',
    rarity: 'mythic',
    buffDescription: '+48 Attack Damage, +50% Valor & +6 HP/sec Regen',
    damageBonus: 48,
    valorMultiplier: 1.5,
    regenPerSec: 6,
    primaryColor: '#0284c7',
    accentColor: '#7dd3fc',
    unlocked: false,
    count: 0,
  },
];

export const INITIAL_MOUNTS: VikingMount[] = [
  {
    id: 'mount_war_bear',
    name: 'Kodiak War Bear',
    title: 'Armored Grizzly of Katfjord',
    rarity: 'rare',
    speedMultiplier: 1.5,
    jumpMultiplier: 1.15,
    priceSilver: 0,
    priceGBP: 0,
    unlocked: true,
    primaryColor: '#78350f',
    accentColor: '#f59e0b',
  },
  {
    id: 'mount_dire_wolf',
    name: 'Frostfang Dire Wolf',
    title: 'Swift Apex Predator of the North',
    rarity: 'legendary',
    speedMultiplier: 1.75,
    jumpMultiplier: 1.3,
    priceSilver: 350,
    priceGBP: 2.99,
    unlocked: false,
    primaryColor: '#475569',
    accentColor: '#38bdf8',
  },
  {
    id: 'mount_sleipnir',
    name: 'Sleipnir Runic Steed',
    title: 'Odin’s Celestial Warhorse',
    rarity: 'mythic',
    speedMultiplier: 2.0,
    jumpMultiplier: 1.5,
    priceSilver: 700,
    priceGBP: 4.99,
    unlocked: false,
    primaryColor: '#1e1b4b',
    accentColor: '#fde047',
  },
];

export const INITIAL_TYCOON_BUILDINGS: TycoonBuilding[] = [
  {
    id: 'tycoon_lumber_mill',
    name: 'Katfjord Waterwheel Lumber Mill',
    description: 'Automated saws harvest pine timber and generate passive Silver.',
    level: 1,
    maxLevel: 5,
    baseCostSilver: 100,
    baseCostWood: 4,
    baseCostIron: 0,
    silverPerSec: 4,
    valorPerSec: 1,
    position: { x: 24, z: 12 },
  },
  {
    id: 'tycoon_runic_forge',
    name: 'Dwarven Runic Smeltery',
    description: 'Smelts mountain iron ore into Norse blades for steady clan income.',
    level: 0,
    maxLevel: 5,
    baseCostSilver: 180,
    baseCostWood: 4,
    baseCostIron: 2,
    silverPerSec: 9,
    valorPerSec: 3,
    position: { x: 24, z: 24 },
  },
  {
    id: 'tycoon_mead_hall',
    name: 'Jarl’s Feast & Mead Hall',
    description: 'Attracts warriors from across the realm, generating Silver & Valor.',
    level: 0,
    maxLevel: 5,
    baseCostSilver: 320,
    baseCostWood: 6,
    baseCostIron: 3,
    silverPerSec: 18,
    valorPerSec: 6,
    position: { x: -24, z: 24 },
  },
  {
    id: 'tycoon_allfather_sanctum',
    name: 'Allfather Golden Treasury',
    description: 'A towering golden obelisk that showers your clan treasury with tribute.',
    level: 0,
    maxLevel: 5,
    baseCostSilver: 550,
    baseCostWood: 8,
    baseCostIron: 5,
    silverPerSec: 35,
    valorPerSec: 14,
    position: { x: -24, z: 12 },
  },
];

export const WEAPON_SKILLS: WeaponSkill[] = [
  {
    id: 'whirlwind',
    key: 'Z',
    name: 'Whirlwind Cleave',
    description: '360° spinning axe slash hitting all nearby enemies & barricades',
    cooldown: 5,
    staminaCost: 15,
  },
  {
    id: 'thunder_leap',
    key: 'X',
    name: 'Thor’s Lightning Leap',
    description: 'Skyward leap and thunderous slam calling down lightning on foes',
    cooldown: 8,
    staminaCost: 25,
  },
  {
    id: 'frost_nova',
    key: 'F',
    name: 'Niflheim Frost Aegis',
    description: 'Freezing shockwave that heals +35 HP, restores Stamina & blasts foes',
    cooldown: 11,
    staminaCost: 20,
  },
];

export const INITIAL_BADGES: AchievementBadge[] = [
  {
    id: 'badge_first_blood',
    title: 'First Blood of Katfjord',
    description: 'Vanquish your first hostile Frostfang Raider or Boss in combat.',
    unlocked: false,
    rewardSilver: 150,
  },
  {
    id: 'badge_shipwright',
    title: 'Captain of the Drakkar',
    description: 'Mount the Viking Longship helm and set sail across the fjord.',
    unlocked: false,
    rewardSilver: 200,
  },
  {
    id: 'badge_obby_master',
    title: 'Valhalla Sky Walker',
    description: 'Ascend the floating Valhalla Sky Obby platforms and reach the summit.',
    unlocked: false,
    rewardSilver: 500,
  },
  {
    id: 'badge_tycoon_jarl',
    title: 'Tycoon Architect',
    description: 'Upgrade at least 3 Village Tycoon structures in Katfjord.',
    unlocked: false,
    rewardSilver: 300,
  },
  {
    id: 'badge_pet_tamer',
    title: 'Tamer of Norse Beasts',
    description: 'Hatch a Runic Companion Egg at the Pet Sanctuary.',
    unlocked: false,
    rewardSilver: 250,
  },
  {
    id: 'badge_outpost_king',
    title: 'Conqueror of Frostfang',
    description: 'Capture the Frostfang Outpost Territory Banner for your clan.',
    unlocked: false,
    rewardSilver: 400,
  },
];

export const INITIAL_TRADE_OFFERS: TradeOffer[] = [
  {
    id: 'trade_floki_timber',
    traderName: 'Floki_Shipwright',
    traderClan: 'Raven Clan',
    giveLabel: '6 Timber Logs',
    giveType: 'wood',
    giveAmount: 6,
    receiveLabel: '180 Silver Coins',
    receiveType: 'silver',
    receiveAmount: 180,
    completed: false,
  },
  {
    id: 'trade_bjorn_iron',
    traderName: 'Bjorn_Ironside',
    traderClan: 'Ironside Clan',
    giveLabel: '3 Iron Ore',
    giveType: 'iron',
    giveAmount: 3,
    receiveLabel: '240 Silver + 120 Valor',
    receiveType: 'valor',
    receiveAmount: 240,
    completed: false,
  },
  {
    id: 'trade_valkyrie_egg',
    traderName: 'Valkyrie_99',
    traderClan: 'Katfjord Clan',
    giveLabel: '220 Silver Coins',
    giveType: 'silver',
    giveAmount: 220,
    receiveLabel: '1 Mythic Runic Pet Egg',
    receiveType: 'pet_egg',
    receiveAmount: 1,
    completed: false,
  },
  {
    id: 'trade_ragnar_supply',
    traderName: 'Ragnar_Lothbrok',
    traderClan: 'Katfjord Clan',
    giveLabel: '120 Silver Coins',
    giveType: 'silver',
    giveAmount: 120,
    receiveLabel: '8 Timber + 4 Iron Ore',
    receiveType: 'wood',
    receiveAmount: 8,
    completed: false,
  },
];

export const RUNE_WHEEL_PRIZES = [
  { id: 'w1', label: '+150 Silver', type: 'silver' as const, amount: 150, color: '#f59e0b' },
  { id: 'w2', label: '+200 Valor', type: 'valor' as const, amount: 200, color: '#0284c7' },
  { id: 'w3', label: '+350 Silver', type: 'silver' as const, amount: 350, color: '#eab308' },
  { id: 'w4', label: '+8 Timber & +4 Iron', type: 'resources' as const, amount: 8, color: '#10b981' },
  { id: 'w5', label: '+500 Silver Jackpot!', type: 'silver' as const, amount: 500, color: '#ef4444' },
  { id: 'w6', label: '+450 Valor Honor', type: 'valor' as const, amount: 450, color: '#8b5cf6' },
];

// 1. Fjord Fishing Fish Species Catalog
export const NORSE_FISH_SPECIES: FishSpecies[] = [
  {
    id: 'fjord_salmon',
    name: 'Golden Fjord Salmon',
    rarity: 'rare',
    minWeight: 3.2,
    maxWeight: 9.8,
    silverValue: 75,
    staminaBoost: 35,
    icon: '🐟',
    description: 'Prized glittering salmon caught in the deep waters of Katfjord Fjord.',
  },
  {
    id: 'abyssal_cod',
    name: 'Niflheim Abyssal Cod',
    rarity: 'epic',
    minWeight: 6.5,
    maxWeight: 18.2,
    silverValue: 120,
    staminaBoost: 50,
    icon: '🐠',
    description: 'Bioluminescent cod from the cold ocean depths near the dragon portals.',
  },
  {
    id: 'arctic_char',
    name: 'Frost Peak Arctic Char',
    rarity: 'uncommon',
    minWeight: 2.1,
    maxWeight: 6.4,
    silverValue: 45,
    staminaBoost: 25,
    icon: '🐡',
    description: 'Hardy freshwater char thriving in icy glacial runoff streams.',
  },
  {
    id: 'runic_trout',
    name: 'Ancient Runic Trout',
    rarity: 'legendary',
    minWeight: 4.8,
    maxWeight: 14.5,
    silverValue: 220,
    staminaBoost: 75,
    icon: '✨',
    description: 'Inscribed with glowing Norse runes granting immense vigor to the consumer.',
  },
  {
    id: 'leviathan_bass',
    name: 'Midgard Sea Bass',
    rarity: 'uncommon',
    minWeight: 5.0,
    maxWeight: 12.0,
    silverValue: 55,
    staminaBoost: 30,
    icon: '🦈',
    description: 'Fierce predatory bass found along the rocky coastlines.',
  },
  {
    id: 'kraken_calamari',
    name: 'Baby Kraken Calamari',
    rarity: 'mythic',
    minWeight: 12.0,
    maxWeight: 32.0,
    silverValue: 450,
    staminaBoost: 100,
    icon: '🦑',
    description: 'Rare tentacled ocean monster spawn hauled from Jörmungandr’s wake.',
  },
];

// 2. Viking Archery & Quiver Arrow Catalog
export const ARROW_TYPES: ArrowDefinition[] = [
  {
    id: 'bodkin',
    name: 'Iron Bodkin Arrow',
    damage: 42,
    element: 'physical',
    description: 'High-velocity armor-piercing iron arrowhead for target practice and combat.',
    color: '#e2e8f0',
  },
  {
    id: 'flame',
    name: 'Muspelheim Fire Arrow',
    damage: 68,
    element: 'fire',
    description: 'Ignites targets on impact, dealing fiery damage over time and exploding target bullseyes.',
    color: '#f97316',
  },
  {
    id: 'frost',
    name: 'Fimbulwinter Frost Arrow',
    damage: 60,
    element: 'frost',
    description: 'Chills and slows enemies by 50%, freezing target zones with icy crystals.',
    color: '#38bdf8',
  },
];

// 3. Player Base Building Blueprints
export const BUILDABLE_BLUEPRINTS: BuildableStructureBlueprint[] = [
  {
    type: 'palisade_wall',
    name: 'Wooden Palisade Wall',
    woodCost: 4,
    ironCost: 0,
    silverCost: 20,
    maxHealth: 450,
    description: 'Heavy timber defensive wall barrier to fortify Katfjord outposts.',
  },
  {
    type: 'watchtower',
    name: 'Viking Archer Watchtower',
    woodCost: 10,
    ironCost: 2,
    silverCost: 75,
    maxHealth: 900,
    description: 'Elevated wooden tower with perimeter viewing platform for ranged defense.',
  },
  {
    type: 'palisade_gate',
    name: 'Reinforced Fortress Gate',
    woodCost: 8,
    ironCost: 4,
    silverCost: 60,
    maxHealth: 700,
    description: 'Hinged spiked log gate allowing friendly clan passage while blocking invaders.',
  },
  {
    type: 'defense_ballista',
    name: 'Automated Defense Ballista',
    woodCost: 12,
    ironCost: 6,
    silverCost: 140,
    maxHealth: 600,
    description: 'Turret that automatically locks on and fires iron bolts at hostile raid invaders.',
  },
  {
    type: 'hearth_bonfire',
    name: 'Great Hearth Bonfire',
    woodCost: 6,
    ironCost: 1,
    silverCost: 35,
    maxHealth: 350,
    description: 'Roaring stone hearth fire that cooks fish and regenerates stamina for nearby clan members.',
  },
  {
    type: 'jarl_throne',
    name: 'Carved Dragonbone Throne',
    woodCost: 14,
    ironCost: 8,
    silverCost: 250,
    maxHealth: 1200,
    description: 'Majestic Jarl throne declaring territorial mastery and boosting clan honor generation.',
  },
];

// 4. Pet Evolution Catalog
export const INITIAL_PET_EVOLUTIONS: Record<PetId, PetEvolutionData> = {
  pet_odin_raven: {
    level: 1,
    currentXp: 40,
    maxXp: 100,
    stage: 1,
    evolvedName: 'Huginn & Muninn Twin Storm Ravens',
    evolvedSpecies: 'Celestial Odin Scouts',
    bonusMultiplier: 2.2,
  },
  pet_fenrir_pup: {
    level: 1,
    currentXp: 25,
    maxXp: 100,
    stage: 1,
    evolvedName: 'Dire Alpha Frostwolf',
    evolvedSpecies: 'Legendary Arctic Alpha',
    bonusMultiplier: 2.5,
  },
  pet_frost_dragon: {
    level: 1,
    currentXp: 60,
    maxXp: 150,
    stage: 1,
    evolvedName: 'Fjord Wyrm Drake Titan',
    evolvedSpecies: 'Mythic Elder Dragon',
    bonusMultiplier: 3.0,
  },
  pet_golden_boar: {
    level: 1,
    currentXp: 10,
    maxXp: 80,
    stage: 1,
    evolvedName: 'Gullinbursti Radiant War Boar',
    evolvedSpecies: 'Divine Freyr Steed',
    bonusMultiplier: 2.0,
  },
};

// 4b. Mount Armored Gear Catalog
export const MOUNT_ARMOR_CATALOG: MountArmorPiece[] = [
  {
    id: 'armor_spiked_headgear',
    name: 'Iron Spiked War Chanfron',
    slot: 'head',
    rarity: 'rare',
    speedBonus: 0.18,
    unlocked: true,
    priceSilver: 180,
    description: 'Frontal horned iron barding protecting your mount and granting +18% charge speed.',
  },
  {
    id: 'armor_runic_saddle',
    name: 'Sleipnir Wind-Runic Saddle',
    slot: 'saddle',
    rarity: 'epic',
    speedBonus: 0.28,
    unlocked: false,
    priceSilver: 340,
    description: 'Embroidered enchanted saddle reducing rider stamina burn and boosting gallop speed by +28%.',
  },
  {
    id: 'armor_frostfire_aura',
    name: 'Frostfire Hoof Aura',
    slot: 'aura',
    rarity: 'legendary',
    speedBonus: 0.40,
    unlocked: false,
    priceSilver: 650,
    description: 'Leaves a trail of icy sparks and flames beneath your mount, increasing max speed by +40%.',
  },
];

// 6. Clan Territory Wars (GvG Battlefields) 3-Tower Control Points
export const CONQUEST_TOWERS: ClanConquestTower[] = [
  {
    id: 'tower_north_spire',
    name: 'North Fjord Spire',
    x: 65,
    z: -70,
    controllingClan: 'Katfjord Clan',
    capturePercent: 100,
    isContested: false,
  },
  {
    id: 'tower_central_bastion',
    name: 'Valhalla Central Bastion',
    x: 95,
    z: -30,
    controllingClan: null,
    capturePercent: 0,
    isContested: true,
  },
  {
    id: 'tower_south_redoubt',
    name: 'South Cliff Redoubt',
    x: 125,
    z: -65,
    controllingClan: 'Ironside Clan',
    capturePercent: 80,
    isContested: false,
  },
];

